### ISSUE TITLE
Command failed with EBADF

### ISSUE THREAD

**Issue by christiangenco** [remotion-dev/remotion#2452]
Recently when running some remotion jobs I've been getting an ffmpeg error at the very end of processing: `Command failed with EBADF`. Though remotion reports all frames have been rendered and encoded my final `video.mp4` file isn't there.

# Bug Report 🐛

I'm running remotion `3.3.100` on macOS 12.5.1 Monterey and ffmpeg 6.0. I haven't yet put together a minimal project that still gets this error in the hopes that this is a simple fix that might not have anything to do with remotion since it seems like the remotion part of actually rendering and encoding the video is succeeding.

Additionally, the `/var/folders/jr/dbp0prg11g7_vsmyhys2p66h0000gn/T/remotion-v3-3-100-assetsb70v685s8f/remotion-assets-dir/08187108230777085.wav` file that seems to be the cause of this error doesn't exist after the command finishes, and neither does the `/var/folders/jr/dbp0prg11g7_vsmyhys2p66h0000gn/T/remotion-v3-3-100-assetsb70v685s8f` parent directory.

Here's a little more context from my `zsh` shell:

```bash
$ /Users/cgenco/projects/multicam/node_modules/.bin/remotion render src/index.ts multicam --timeout 1000000 --props={} '/Users/cgenco/videos/2023-05-25 asia 05/video.mp4'
(1/3) ╭───────────────────╮ Bundled code 5630ms
    + ╭───────────────────╮ Copying public dir 4873ms
Entry point = src/index.ts (argument passed - found in cwd), Composition = multicam (Passed as argument), Codec = h264 (derived from out name), Output = /Users/cgenco/videos/2023-05-25 asia 05/video.mp4
(2/3) ╭───────────────────╮ Rendered frames (5x) 12529374ms
    + ╭───────────────────╮ Downloading 2 files
(3/3) ╭───────────────────╮ Encoding video 91157/91157
An error occurred:
Error: Command failed with EBADF: ffprobe -v error -show_entries stream=channels:format=duration -of default=nw=1 /var/folders/jr/dbp0prg11g7_vsmyhys2p66h0000gn/T/remotion-v3-3-100-assetsb70v685s8f/remotion-assets-dir/08187108230777085.wav
spawn EBADF
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:757:9)
    at execa (/Users/cgenco/projects/multicam/node_modules/execa/index.js:83:26)
    at getAudioChannelsAndDurationUnlimited (/Users/cgenco/projects/multicam/node_modules/@remotion/renderer/dist/assets/get-audio-channels.js:23:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
```

I'd love any help in debugging this! If putting together a minimal failing project would help I can do that but it'd be some work I'd like to avoid if possible.

**Comment by JonnyBurger** [comment]
Wow interesting, it fails with a rare error code `EBADF`. 

This should never happen and indicates an error in Node.JS.
Maybe https://github.com/nodejs/node/issues/25335?

Could you let me know your Node version?

**Comment by christiangenco** [comment]
I'm on node `v19.8.1`.

I'm having a lot of trouble making a minimal working example for this bug—it doesn't happen with the exact same project if I limit the number of rendered frames.

Is there anything else you can think of that I could try?

**Comment by JonnyBurger** [comment]
Interesting!

Let's try to think about reasons why `EBADF` could occur - it means "Bad file descriptor", meaning `ffprobe` is somehow a bad file descriptor?

Is there anything special about this binary? Does it only get downloaded before the render (maybe incomplete / still in macOS quarantine)?

Do you render multiple things at once or have other processes running?
Can you reliably run `ffprobe` on your system?

In Remotion 4.0, we will not rely on the system-installed `ffprobe` anymore. Instead, we ship our version that is confirmed running. Maybe this can also solve the problem (https://v4.remotion.dev/docs/4-0-alpha or official launch on July 3)

**Comment by JonnyBurger** [comment]
Interesting, it must definitely be a Node bug then (maybe fixed by https://github.com/nodejs/node/pull/44461)

I share your excitement! ✌️
I think there is nothing we can do, so closing this issue. But I will link this issue if someone gets a EBADF error in the future.

**Comment by JonnyBurger** [comment]
faaf50ceec4dfa83308651d1dfcf3e9140d0e792

**Comment by rommyarb** [comment]
I can confirm that by switching to the old Node.js 16.x, the EBADF error has gone. The video rendered successfully 🎉
It's surprising that this error still occurs today.

**Comment by thecmdrunner** [comment]
@JonnyBurger I can reproduce this bug in Remotion 4.0.327, in both Node v20 and v22.
Unfortunately switching to Node 16.x isn't possible.

My Video is quite simple:

```tsx
import {
  AbsoluteFill,
  Audio,
  interpolate,
  Series,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
  Video,
} from "remotion";

export const HelloWorld = () => {
  const frame = useCurrentFrame();
  const { durationInFrames, fps } = useVideoConfig();

  const offset = -51 * fps;
  const videoSpeed = 1.125;

  const musicVolume = interpolate(frame, [550, 570], [0.24, 0.2], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <Series>
      <Series.Sequence durationInFrames={fps}>
        <AbsoluteFill></AbsoluteFill>
      </Series.Sequence>

      <Series.Sequence
        offset={offset}
        durationInFrames={durationInFrames + Math.abs(offset)}
      >
        <Audio loop volume={musicVolume} src={staticFile("bg-music.mp3")} />

        <AbsoluteFill className="bg-white">
          {/* Face cam */}
          <div className="absolute left-12 bg-white bottom-20 z-10 rounded-full size-[20rem] border-2 border-blue-500 overflow-hidden shadow-2xl">
            <Video
              muted
              playbackRate={videoSpeed}
              className="w-full scale-125 pr-5 bg-white h-full min-h-full min-w-full object-cover object-center"
              src={staticFile("face-aligned.mov")}
            />
          </div>

          {/* Screen Record */}
          <div
            style={{
              width: `${1920 * 0.97}px`,
            }}
            className="m-auto bg-white flex items-center justify-center overflow-hidden"
          >
            <Video
              playbackRate={videoSpeed}
              style={{
                width: "1920px",
                minWidth: "1920px",
              }}
              className="h-full min-h-full object-cover object-center"
              src={staticFile("screen-record-aligned.mov")}
            />
          </div>
        </AbsoluteFill>
      </Series.Sequence>
    </Series>
  );
};

// Root.tsx

const FPS = 30

<Composition
        id="HelloWorld"
        component={HelloWorld}
        durationInFrames={179 * FPS}
        fps={FPS}
        width={1920}
        height={1080}
      />

```
