### ISSUE TITLE
SIGSEGV during rendering

### ISSUE THREAD

**Issue by mcgloneleviWISTIA** [remotion-dev/remotion#5470]
Hello Remotion!

I am a software engineer at Wistia.  We have run into an issue with a video that is causing a SIGSEGV during rendering.

# Bug Report 🐛

Here's the stack trace:

```
Compositor exited with signal SIGSEGV
    at ChildProcess.<anonymous> (/var/task/index.js:102483:41)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at ChildProcess.<canonymous> (/var/task/index.js:102483:41)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Compositor exited with signal SIGSEGV
    at ChildProcess.<anonymous> (/var/task/index.js:102483:41)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at ChildProcess.<anonymous> (/var/task/index.js:102483:41)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at execute (https://remotion-files.wistia.land/prod/sites/wistia-remotion/2025/06/18/v-4.0.245/991c64711dd5b5b26f5d3c930b09de493ba3b6d2/bundle.js:9306:35)
```

Let me know if there is more information I can supply to help troubleshoot this issue.

**Comment by mcgloneleviWISTIA** [comment]
Update on this.  We tried upgrading Remotion from 4.0.291 to 4.0.319 and we still have the segfault.

**Comment by JonnyBurger** [comment]
Yes, this requires some more information for me to debug.

Can you submit the offending video? Either here or via https://remotion.dev/report

**Comment by mcgloneleviWISTIA** [comment]
> Yes, this requires some more information for me to debug.
> 
> Can you submit the offending video? Either here or via https://remotion.dev/report

I will reach out to our customer service team to get permission from the customer to share their video files.

**Comment by mcgloneleviWISTIA** [comment]
Update: We're still waiting on permission from the customer.  If we don't hear back from them soon I will close this ticket.

**Comment by JonnyBurger** [comment]
Thank you! Although I got a different error, I was able to produce a crash with Clip 6 which is now fixed. 

I'll release a new version today or tomorrow, let me know should it not resolve the error.

**Comment by mcgloneleviWISTIA** [comment]
We are still getting a segfault:

```
remotion segproc stderr: 3-days-0c7218h7hi error 0: renderer: Compositor exited with signal SIGSEGV
    at ChildProcess.<anonymous> (/var/task/index.js:135:723)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at ChildProcess.<anonymous> (/var/task/index.js:135:723)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
3-days-0c7218h7hi error 1: stitcher: Error: Compositor exited with signal SIGSEGV
    at ChildProcess.<anonymous> (/var/task/index.js:135:723)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at ChildProcess.<anonymous> (/var/task/index.js:135:723)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at execute (https://remotion-files.wistia.land/prod/sites/wistia-remotion/2025/06/27/v-4.0.245/1c059098fedfc03feb8f1f266090f1cbd59a0e14/bundle.js:9306:35
```

I have some videos that I can send you that may be able to exercise this case.

**Comment by JonnyBurger** [comment]
@mcgloneleviWISTIA Is this on Remotion Lambda? Or something custom?

Since I never actually got `SIGSEGV` and you did, I need to know if you customized anything about the Linux runtime and/or FFmpeg.

SIGSEGV stands for segmentation fault which means memory corruption in the Rust/FFmpeg code.  
Very strange, as this points to there being an issue on the OS / libc / FFmpeg / Rust level.

**Comment by mcgloneleviWISTIA** [comment]
I reached out to some folks internally who maintain our encoding stack.  Here was their reply:

```
Unless the video is very large, we generally use a stock Remotion Lambda image. Instant HLS will try to do it on Ubuntu.

For the video in question, I can tell it was using Remotion Lambda because of details in the stack trace.

We shell out to javascript there, and then the javascript invokes Remotion Lambda, and we just wait for the output of that in segproc before continuing.
```

**Comment by JonnyBurger** [comment]
Thanks for that, I was now able to reproduce (only happens on Linux).

Here is an explanation of what is happening: #5489

The video you used I consider corrupt, because the dimensions in the metadata of the video do not align with the size of the data.

The video changes its dimensions from 1718px to 1714px inmidst the video, maybe because of a bug in the screen recorder or because a window was resized and the screen recorder is in window capture mode.

Check on your side as well if you are prepared to handle such videos.

**Comment by mcgloneleviWISTIA** [comment]
My team and I looked into this, and I think we may have found the code change in Chromium that introduced this issue:

https://chromium.googlesource.com/chromium/src/+/5b308896c5e4f4810a5cc52d263dfd628a25cc3e%5E%21/#F6

It looks like a change in C++ types to use HeapArray which is more memory-safe than what they were doing previously with pointers and statically-calculated sizes.  (My C++ knowledge is not great, so I may be a little off here.). Either way, stuff changed with YUV calculations in that commit and it appears to be causing issues for our users.
